# Generated by Django 2.2.5 on 2019-12-25 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('b_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'branch',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'company',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('d_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('e_id', models.AutoField(primary_key=True, serialize=False)),
                ('e_name', models.CharField(max_length=50)),
                ('e_email', models.CharField(max_length=50)),
                ('com_name', models.CharField(max_length=50)),
                ('branch_name', models.CharField(max_length=50)),
                ('com_loc', models.CharField(max_length=50)),
                ('dep_name', models.CharField(max_length=50)),
                ('dep_loc', models.CharField(max_length=50)),
                ('b_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='accounts.Department')),
                ('c_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='accounts.Company')),
                ('d_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='accounts.Branch')),
            ],
            options={
                'db_table': 'employee',
            },
        ),
    ]
