# Generated by Django 2.2.5 on 2019-12-25 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='b_id',
            new_name='b',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='c_id',
            new_name='c',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='d_id',
            new_name='d',
        ),
    ]
